### ISSUE TITLE
Issues with the Set up

### ISSUE THREAD

**Issue by Layman2501** [plexstreams/plex-auto-scan#4]
Hello,

I followed the instructions and appsetting example.
How ever I am running into the following issue 

Google.Apis.Requests.RequestError

Shared drive not found: 1KhHa0OScw1Zfopo424xSf3tbbKSfCq [404]
Errors [
        Message[Shared drive not found: 1KhHa0OScw1Zfopo424xSf3tbbKS] Location[driveId - parameter] Reason[notFound] Domain[global]
]

I got the drive id following 
https://umzuzu.com/blog/2019/9/30/how-to-get-the-id-of-a-google-shared-drive-formerly-team-drives

is there something else I am missing with the API's other than generating a oauth? client id and share?

**Comment by plexstreams** [comment]
Make sure you're using a Team Drive and that oauth credentials you are using can access the drive. I would use Rclone to setup a remote and that will give you information you need in rclone.conf which you can then use to add to appsettings.json.

https://rclone.org/drive/

**Comment by Layman2501** [comment]
I do have rclone set up. I guess because its not a team drive thats the issue.

**Comment by plexstreams** [comment]
Yes, this only works with Team/Shared drives and not your personal Google Drive.
